/*
 Copyright 2011-2013, github.com/termi/HTML5-History-API, original by Dmitriy Pakhtinov ( spb.piksel@gmail.com ) */
void function(){var l=void 0,n=null,q=!1;function C(a){if(!a.__history_shim__){var p=h();if(D)return E=p.a,D=0;var c=a.oldURL||E;a=E=a.newURL||p.a;var p=c.replace(/^.*?(#|$)/,""),b=a.replace(/^.*?(#|$)/,"");c!=a&&!F&&t(l);r=F=0;p!=b&&t(2,c,a)}}function $(a){var p=a||q,c=p.target||q;a=p.defaultPrevented;if(c&&("A"===c.nodeName&&!a)&&(a=h(c.getAttribute("href",2),!0),a.b&&"#"!==a.b&&a.b===a.a.replace(h().a.split("#").shift(),""))){history.location.hash=a.b;a=a.b.replace(/^#/,"");if((c=document.getElementById(a))&&c.id===a&&
"A"===c.nodeName)c=c.getBoundingClientRect(),window.scrollTo(G.scrollLeft||0,c.top+(G.scrollTop||0)-(G.clientTop||0));p.preventDefault()}}function H(a){r===f.href&&(a.stopImmediatePropagation?a.stopImmediatePropagation():a.stopPropagation(),r=0);d.removeEventListener("popstate",H,q);H=n}function t(a,p,c){var b=new u(2==a?"hashchange":3==a?"pagechange":"popstate");p!=l&&(b.oldUrl=p);c!=l&&(b.newUrl=c);b.__history_shim__=!0;if(!j&&a==l&&d.onpopstate)d.onpopstate(b);d.dispatchEvent(b)}function I(a){return x?
a?x.setItem("__history_shim__",aa(a)):ba(x.getItem("__history_shim__"))||{}:{}}function y(a,b,c){return z?(z(a,b),a):c?a:l}function N(a,b,c,d){var e=I(),g=h().a,k=c&&h(c);r=0;c=k?k.a:g;d&&e[g]&&delete e[g];if((!j||ca)&&x&&a)e[c]=a,I(e),a=n;O&&P?d?P.call(this,a,b,c):O.call(this,a,b,c):k&&k.d!=h().d&&(D=1,d?f.replace("#"+k.g):f.hash=k.g);a=h().c;if(!m||m!=a)t(3,m,a),m=a}function Q(a,b,c){this.pushState(a,b,c,1)}var d=this,b=d.JSON||{},ba=b.parse,aa=b.stringify,A=document,G=A.documentElement,u=d.j,e=
Function.prototype.bind||q,R=e.call(Function.prototype.call,Object.prototype.hasOwnProperty),s=d.history||{},e=(b=d.history)&&(b=b.__proto__||(b=b.constructor)&&b.prototype)&&b&&b!=Object.prototype&&b||d.history,f=d.location,j="pushState"in s,ca=j&&s.state===l,r=f.href,O=s.pushState,P=s.replaceState,x=d.sessionStorage,z;if(b=Object.defineProperty&&function(a,b){var c,d;for(d in b)R(b,d)&&(c=b[d],"object"!=typeof c&&(c={value:c}),"configurable"in c||(c.configurable=!0),Object.defineProperty(a,d,c))}){try{b(e,
{_:{get:function(){return 1},configurable:!0}})}catch(ga){b=n}1!==e._&&(b=n);"_"in e&&delete e._}!b&&e.__defineGetter__&&(b=function(a,b){var c,d;if(a.__defineGetter__)for(d in b)R(b,d)&&(c=b[d],c.get&&a.__defineGetter__(d,c.get),c.set&&a.__defineSetter__(d,c.set));return a});z=b;var da=A.documentMode&&/msie (\d+)/i.test(navigator.userAgent),J=l,D=0,ea=/[^\/]+$/g,S=location.pathname.split("#")[0].split("?")[0],h,g=A.createElement("a"),T,K,U,L,B,v,k,fa=/^[^#]*/;h=function(a,b){if(a){if(!j||J||da){var c=
h(),d=c.e,e=c.i,m=a.charAt(0);a=/^(?:[\w0-9]+\:)?\/\//.test(a)?"/"==m?e+a:a:e+"//"+c.h+("/"==m?a:"?"==m?d+a:"#"==m?d+c.f+a:d.replace(ea,"")+a)}}else if(a=f.href,!j||b)a=f.protocol+"//"+f.host+(-1!=a.indexOf("#")?"/":S)+(a.replace(fa,"")||"#").replace(/^#[\/]?(?:\/)?/,"");if(T!==a){g.href=T=a;v=g.port;B=g.host;k=g.pathname;if("http:"===g.protocol&&80==v||"https:"===g.protocol&&443==v)B=g.hostname,v="";k="/"==k.charAt(0)?k:"/"+k;K=k+g.search+g.hash;L=k+g.search;U=L+g.hash}return{a:g.protocol+"//"+B+
K,i:g.protocol,h:B,k:g.hostname||f.hostname,l:v||f.port,e:k,f:g.search,b:g.hash,d:K,c:L,g:U}};var e=!J&&e,V=q,b={state:{get:function(){return I()[this.location.href]||n}},length:{get:function(){return s.length}},location:{set:function(a){d.location.href=a},get:function(){return j?f:M}}},M={assign:function(a){f.assign(j||0!==a.indexOf("#")?a:"#"+h().c+a)},reload:f.reload,replace:function(a){f.replace(j||0!==a.indexOf("#")?a:"#"+h().c+a)},toString:function(){return this.href}},X={href:{set:function(a){f.href=
a},get:function(){return h().a}},protocol:{set:function(a){f.protocol=a},get:function(){return f.protocol}},host:{set:function(a){f.host=a},get:function(){return f.host}},hostname:{set:function(a){f.hostname=a},get:function(){return f.hostname}},port:{set:function(a){f.port=a},get:function(){return f.port}},pathname:{set:function(a){f.pathname=a},get:function(){return h().e}},search:{set:function(a){f.search=a},get:function(){return h().f}},hash:{set:function(a){a=0===a.indexOf("#")?a:"#"+a;var b=
h();j?f.hash="#"+b.c+a:a!=b.b&&((V||s).pushState(n,n,b.c+a),W({oldURL:b.a}))},get:function(){return h().b}},origin:{}},W,Y=d.onpopstate||n,w=d.onhashchange,F=0,Z=h(),E=Z.a;d.addEventListener("hashchange",C,q);w===l&&setInterval(function(){C({})},100);w||(w=n);d.addEventListener&&j&&(d.addEventListener("popstate",H,q),d.addEventListener("popstate",function(){r=0;F=1},q));e&&y(e,s.state===l?{state:b.state,location:b.location}:{location:b.location});M=y(M,X);"onpopstate"in d||y(d,{onhashchange:{get:function(){return w},
set:function(a){w=a||n}},onpopstate:{get:function(){return Y},set:function(a){if(Y=a||n)if(!j&&r&&!(r=0)&&Z.d!==S)clearInterval(n),setTimeout(t,10)}}},!0);j||document.addEventListener("click",$,q);W=C;try{new u("click")}catch(ha){u=n}u||(u=function(a){var b;b=A.createEvent("Events");b.initEvent(a,q,q);return b});e.pushState=N;e.replaceState=Q;e.emulate=!j;var m="",b=function(){var a=h().c;if(!m||m!=a)m=a,t(3,m,a)};j&&d.addEventListener("popstate",b);d.addEventListener("hashchange",b);if(d.opera&&
j&&(b=document.createElement("a"),e=b.__proto__))(b=Object.getOwnPropertyDescriptor(b,"href"))&&"get"in b&&Object.defineProperty(e,"href",function(a){this.get=function(){var b=this.getAttribute("href"),c;return b&&"/"==b[0]?(c=d.location,c=c.protocol+"//"+c.host,c+b):a.call(this)};return this}.call(b,b.get));b=J=y=z=e=V=b=X=e=e=N=Q=n}.call(window);
