/* Copyright 2011-2013, github.com/termi/HTML5-History-API, original by Dmitriy Pakhtinov ( spb.piksel@gmail.com ) */
(function(){"use strict";function O(D){return function(){return D}}function D(a){var c=a||b.event,f=c.target||c.srcElement;a="defaultPrevented"in c?c.defaultPrevented:!1===c.returnValue;f&&"A"===f.nodeName&&!a&&(a=h(f.getAttribute("href",2),!0),a.b&&"#"!==a.b&&a.b===a.a.replace(h().a.split("#").shift(),"")&&(E=!0,history.location.hash=a.b,a=a.b.replace(/^#/,""),(f=document.getElementById(a))&&f.id===a&&f.scrollIntoView(),c.preventDefault?c.preventDefault():c.returnValue=!1))}function T(a,c,f,b){var e=f&&h(f);l&&(b||e&&e.a==h().a?I.call(this,a,c,f):t&&
e&&"/"==e.e?(J.call(this,a,c,f+"?"),I.call(this,a,c,f)):J.call(this,a,c,f));if(!U){c=P();var p=h().a,e=f&&h(f);u=!1;f=e?e.a:p;b&&c[p]&&delete c[p];Q&&(c[f]=a,P(c))}!l&&e&&e.f!=h().f&&(E=!0,b?k.replace("#"+e.d):k.hash=e.d);a=h().c;x&&x==a||(K(3,x,a,!0),x=a)}function V(a,c,f){T.call(this,a,c,f,!0)}var b=this,g=b.history||{};if(!0!==g.__history_shim__){var d,m=document,$=m.documentElement,W=Function.prototype.call,R=Function.prototype.bind||!1,aa=m.documentMode&&/msie (\d+)/i.test(navigator.userAgent),
t=(d=b.opera)&&"function"==typeof(d=d.version)&&+d(),q;if(!b.addEventListener||10>t)q={popstate:{},hashchange:{}},q.onpopstate=q.popstate,q.onhashchange=q.hashchange,q.onpagechange=q.pagechange={},d=b.addEventListener?"addEventListener":"attachEvent",b[d]=R.call(function(a,c,f){var s,e;c in q&&(e=q[c],(s=f.uuid)||(s=f.uuid="_"+ +new Date),e[s]||(e[s]=f));W.call(a,b,c,f,!1)},b,b[d]),d=b.addEventListener?"removeEventListener":"detachEvent",b[d]=R.call(function(a,c,f){var s,e;c in q&&(s=f.uuid)&&(e=
q[c])&&delete e[s];W.call(a,b,c,f,!1)},b,b[d]);d=b.JSON||{};var ba=d.parse,X=d.stringify,F=b.Event,G=R.call(W,Object.prototype.hasOwnProperty),z=(d=b.history)&&(d=d.__proto__||(d=d.constructor)&&d.prototype)&&d&&d!=Object.prototype&&d||b.history,k=b.location,u=!t&&!aa&&k.href,J=g.pushState,I=g.replaceState,l=!(!J||!I),U=l&&"state"in g,Q=b.sessionStorage,L=function(){var a=Object.defineProperty&&function(a,c){var e,b;for(b in c)G(c,b)&&(e=c[b],"object"!=typeof e&&(e={value:e}),"configurable"in e||(e.configurable=
!0),Object.defineProperty(a,b,e))};if(a){try{a(z,{_:{get:O(1),configurable:!0}})}catch(c){a=null}1!==z._&&(a=null);"_"in z&&delete z._}!a&&z.__defineGetter__&&(a=function(a,c){var e,b;if(a.__defineGetter__)for(b in c)G(c,b)&&(e=c[b],e.get&&a.__defineGetter__(b,e.get),e.set&&a.__defineSetter__(b,e.set));return a});return a}(),w=!L&&b.execScript&&(new Date).getTime()||void 0,n=w?m.createElement("iframe"):void 0,ea=/[^\/]+$/g,ca=location.pathname.split("#")[0].split("?")[0],h=function(a){var c,b,d,e,
p,g,v,fa=/^[^#]*/;return function(r,m){if(!r){if(r=k.href,!l||m)r=k.protocol+"//"+k.host+(-1!=r.indexOf("#")?"/":ca)+((r.replace(fa,"")||"#").replace(/^#[\/]?(?:\/)?/,"")||k.search)}else if(!l||w||aa){var n=h(),q=n.e,u=n.l,t=r.charAt(0);r=/^(?:[\w0-9]+\:)?\/\//.test(r)?"/"==t?u+r:r:u+"//"+n.k+("/"==t?r:"?"==t?q+r:"#"==t?q+n.g+r:q.replace(ea,"")+r)}if(c!==r){a.href=c=r;g=a.port;p=a.host;v=a.pathname;if("http:"===a.protocol&&80==g||"https:"===a.protocol&&443==g)p=a.hostname,g="";v="/"==v.charAt(0)?
v:"/"+v;b=v+a.search+a.hash;e=v+a.search;d=e+a.hash}return{a:a.protocol+"//"+p+b,l:a.protocol,k:p,n:a.hostname||k.hostname,o:g||k.port,e:v,g:a.search,b:a.hash,f:b,c:e,d:d}}}(m.createElement("a")),A=!w&&z,B=!A&&{back:g.back,forward:g.forward,go:g.go,pushState:T,replaceState:V,emulate:!l,toString:O("[object History]")},y={state:{get:function(){return n&&n.storage||P()[this.location.href]}},length:{get:function(){return g.length}},location:{set:function(a){b.location.href=a},get:function(){return l?
k:M}}},M={assign:function(a){k.assign(l||0!==a.indexOf("#")?a:"#"+h().c+a)},reload:k.reload,replace:function(a){k.replace(l||0!==a.indexOf("#")?a:"#"+h().c+a)},toString:function(){return this.href}},S={href:{set:function(a){k.href=a},get:function(){return h().a}},protocol:{set:function(a){k.protocol=a},get:function(){return k.protocol}},host:{set:function(a){k.host=a},get:function(){return k.host}},hostname:{set:function(a){k.hostname=a},get:function(){return k.hostname}},port:{set:function(a){k.port=
a},get:function(){return k.port}},pathname:{set:function(a){k.pathname=a},get:function(){return h().e}},search:{set:function(a){k.search=a},get:function(){return h().g}},hash:{set:function(a){a=0===a.indexOf("#")?a:"#"+a;var c=h();l?k.hash="#"+c.c+a:a!=c.b&&((B||g).pushState(null,null,c.c+a),H({oldURL:c.a}))},get:function(){return h().b}},origin:{}},ga=function(a){if(!Object.defineProperty)return a;try{if(Object.defineProperty(a,"_",{get:O(1),configurable:!0}),1===a._)return delete a._,a}catch(c){}var b=
document.createElement("a"),d;for(d in b)try{delete b[d]}catch(e){}for(d in a)b[d]=a[d];return b},N=function(a,c,f){if(L)return L(a,c),a;if(f)return a;if(!f&&w){f="StaticClass"+w++;var d=["Class "+f],e;"execVB"in b||b.execScript("Function execVB(c) ExecuteGlobal(c) End Function","VBScript");"VBCVal"in b||b.execScript("Function VBCVal(o,r) If IsObject(o) Then Set r=o Else r=o End If End Function","VBScript");for(e in a)G(a,e)&&d.push("Public ["+e+"]");G(a,"toString")&&(a.propertyIsEnumerable("toString")||
d.push("Public [toString]"),c["(toString)"]={get:function(){return this.toString.call(this)}});for(e in c)G(c,e)&&(c[e].get&&(a["get "+e]=c[e].get,d.push("Public [get "+e+"]","Public "+("(toString)"===e?"Default ":"")+"Property Get ["+e+"]","Call VBCVal(me.[get "+e+"].call(me),["+e+"])","End Property")),c[e].set&&(a["set "+e]=c[e].set,d.push("Public [set "+e+"]","Public Property Let ["+e+"](v)","Call me.[set "+e+"].call(me,v)","End Property","Public Property Set ["+e+"](v)","Call me.[set "+e+"].call(me,v)",
"End Property")));d.push("End Class","Function "+f+"Factory()","Set "+f+"Factory=New "+f,"End Function");b.execVB(d.join("\n"));d=b[f+"Factory"]();for(e in a)d[e]=a[e];G(a,"toString")&&(d.toString=a.toString)}return d},P=function(a){if(a)try{Q.setItem("__history_shim__",X(a))}catch(c){}else return Q&&ba(Q.getItem("__history_shim__"))||{}},K=function(a,c,d,k){var e=new F(2===a?"hashchange":3===a?"pagechange":"popstate"),p;void 0!==c&&(e.oldUrl=c);void 0!==d&&(e.newUrl=d);e.__history_shim__=!0;if(!l&&
void 0==a&&b.onpopstate)b.onpopstate(e);else 3===a&&(e.popstate=!k,da||"function"!==typeof(p=b.onpagechange)||p.call(b,e));if(!b.dispatchEvent||10>t){if(a=q[e.type])for(var h in a)a.hasOwnProperty(h)&&("function"===typeof(p=a[h])||p&&"object"===typeof p&&(p=p.handleEvent))&&p.call(b,e)}else b.dispatchEvent(e)},H,E=!1,da;(function(){function a(){u&&!(u=!1)&&n.f!==ca&&(clearInterval(p),setTimeout(K,10))}function c(a){a&&u===k.href&&(a.stopImmediatePropagation?a.stopImmediatePropagation():a.stopPropagation());
u=!1;b.removeEventListener("popstate",c,!1);c=null}var f=b.onpopstate||null,s=b.onhashchange,e=!1,p=null,n=h(),v=n.a;H=function(a){if(!a.__history_shim__){var c=h();if(E)return v=c.a,E=!1;var b=a.oldURL||v;a=v=a.newURL||c.a;var c=b.replace(/^.*?(#|$)/,""),d=a.replace(/^.*?(#|$)/,"");b==a||e||K(void 0);u=e=!1;c!=d&&K(2,b,a)}};l?b.addEventListener&&("complite"!==m.readyState?(u?(b.addEventListener("popstate",c,!1),b.addEventListener("load",function(){setTimeout(c,0)},!1)):c=null,b.addEventListener("popstate",
function(a){u=!1;e=!0;t&&I.call(g,a.state,document.title,location.href)},!1)):u=!1):(b.addEventListener?b.addEventListener("hashchange",H,!1):b.attachEvent("onhashchange",H),void 0===s&&setInterval(function(){H({})},100),s||(s=null));y.__history_shim__={get:O(!0)};A?((d=m.createElement("a"),d.href="http://g.g/%25","/%"===d.pathname)&&"URL"in m&&(y.location.get=function(){return M},S.href.get=function(){return m.URL},S.pathname.get=function(){var a=this.href,c=this.hash,b=this.host;return a.substr(a.indexOf(b)+
b.length).replace(this.search,"").replace(c,"")},U||(y.state.get=function(){return P()[b.location.href]})),d={},d.location=y.location,U||(d.state=y.state),d.__history_shim__=y.__history_shim__,N(A,d)):w&&(B=N(B,y));M=N(L?ga(M):M,S);w&&b.execScript("Public history, onhashchange","VBScript");"onpopstate"in b||N(b,{onhashchange:{get:function(){return s},set:function(a){s=a||null}},onpopstate:{get:function(){return f},set:function(c){(f=c||null)&&!l&&a()}}},!0)||l||(p=setInterval(function(){b.onpopstate&&
a()},100));l||(document.addEventListener?document.addEventListener("click",D,!1):document.attachEvent("onclick",D))})();try{new F("click")}catch(ha){F=null}F||(F=function(a){var c;m.createEvent?(c=m.createEvent("Events"),c.initEvent(a,!1,!1)):(c=m.createEventObject(),c.type=a);return c});da=void 0!==$.dispatchEvent&&(!t||10<t)&&function(a){var c=!1;a.dispatchEvent&&(a.onpagechange=function(){c=!0},a.dispatchEvent(new F("pagechange")));return c}(document.createElement("_"));w||(A.pushState=T,A.replaceState=
V);w?(b.history=B,function(a,c){var d,g;if(n&&(g=function(){var a=h().a;c!=a&&H({oldURL:c,newURL:c=a})},d=setInterval(g,100),n.src="javascript:true;",n=$.firstChild.appendChild(n).contentWindow,B.pushState=function(a,b,e,l,m){var q=n.document;if(e=e&&h(e)){m||clearInterval(d);if(l)n.lfirst?(history.back(),B.pushState(a,b,e.a,0,1)):(n.storage=a,k.replace("#/"+e.d));else if(e.a!=c||m)n.lfirst||(n.lfirst=1,B.pushState(n.storage,b,c,0,1)),a=["<script>","lfirst=1;",0,"storage="+X(a)+";","\x3c/script>"],
a[2]='parent.location.hash="'+e.d.replace(/"/g,'\\"')+'";',q.open(),q.write(a.join("")),q.close();m||(c=h().a,d=setInterval(g,100))}else n.storage=a},b.attachEvent("onunload",function(){if(n.storage){var a={};a[h().a]=n.storage;m.cookie="__history_shim__="+escape(X(a))}clearInterval(d)}),1<a.length)){a=unescape(a.pop().split(";").shift());try{n.storage=ba(a)[h().a]}catch(e){}}}(m.cookie.split("__history_shim__="),h().a)):A.emulate=!l;l&&t&&Object.defineProperty&&Object.getOwnPropertyDescriptor&&((d=
Object.getOwnPropertyDescriptor(b.location,"pathname"))&&(d.get=function(){var a=this.href,c=this.hash,b=this.host;return a.substr(a.indexOf(b)+b.length).replace(this.search,"").replace(c,"")}),d&&(b.Location&&b.Location.prototype&&Object.defineProperty(b.Location.prototype,"pathname",d),Object.defineProperty(b.location,"pathname",d)));var C=[],Y=!1,Z=!1;l&&b.chrome&&(d=function(a){var b,d;if(!1===l)!0===E?(d=!0,"hashchange"===a.type&&(E=!1)):"popstate"===a.type&&C.pop();else if(!0===Y)for(Y=!1,d=
!0;b=C.shift();)J.call(g,b.h,b.i,b.j);else!0===Z&&(Z=!1,d=!0);d&&(a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation())},b.addEventListener("popstate",d,!0),b.addEventListener("hashchange",d,!0),d=function(){var a="fullscreenEnabled"in m?m.fullscreenEnabled:m.webkitIsFullScreen;if(a&&l)l=!1,document.addEventListener("click",D,!0),a=function(a,b){var d;J.call(this,a,b,window.location.href);d=this.replaceState.__origin.apply(this,arguments);C.push({j:this.location.href,h:a,i:b});
return d},a.__origin=g.pushState,g.pushState=a,a=function f(a,b){var d;I.call(this,a,b,window.location.href);d=f.__origin.apply(this,arguments);C[C.length-1]={j:this.location.href,h:a,i:b};return d},a.__origin=g.replaceState,g.replaceState=a,C=[];else if(!a&&!l){if(a=g.pushState.__origin)if(g.pushState=a,g.replaceState=g.replaceState.__origin,a=C.length)Z=Y=!0,g.go(-1*a);l=!0;document.removeEventListener("click",D,!0)}},m.addEventListener("webkitfullscreenchange",d),m.addEventListener("webkitfullscreenerror",
d));var x=h().c;d=function(){var a=h().c;x&&x==a||K(3,x,x=a)};b.addEventListener?(b.addEventListener("popstate",d,!1),b.addEventListener("hashchange",d,!1)):(b.attachEvent("popstate",d),b.attachEvent("hashchange",d));d=w=N=L=R=y=S=z=A=V=null}}).call(window);
