/*
 Copyright 2011-2013, github.com/termi/HTML5-History-API, original by Dmitriy Pakhtinov ( spb.piksel@gmail.com ) */
void function(){"use strict";var m=void 0,p=!0,w=null,D=!1;
function N(a){if(!a.__history_shim__){var f=j();if(U)return V=f.a,U=0;var d=a.oldURL||V;a=V=a.newURL||f.a;var f=d.replace(/^.*?(#|$)/,""),c=a.replace(/^.*?(#|$)/,"");d!=a&&!W&&G(m);z=W=0;f!=c&&G(2,d,a)}}function ia(){if(z&&!(z=0)&&ja.f!==ka)clearInterval(la),setTimeout(G,10)}function ma(a){var f=a||c.event,d=f.target||f.srcElement;a="defaultPrevented"in f?f.defaultPrevented:f.returnValue===D;if(d&&("A"===d.nodeName&&!a)&&(a=j(d.getAttribute("href",2),p),a.b&&"#"!==a.b&&a.b===a.a.replace(j().a.split("#").shift(),
""))){history.location.hash=a.b;a=a.b.replace(/^#/,"");if((d=document.getElementById(a))&&d.id===a&&"A"===d.nodeName)d=d.getBoundingClientRect(),window.scrollTo(O.scrollLeft||0,d.top+(O.scrollTop||0)-(O.clientTop||0));f.preventDefault?f.preventDefault():f.returnValue=D}}function X(a){z===g.href&&(a.stopImmediatePropagation?a.stopImmediatePropagation():a.stopPropagation(),z=0);c.removeEventListener("popstate",X,D);X=w}function G(a,f,d){var s=new H(2==a?"hashchange":3==a?"pagechange":"popstate");f!=
m&&(s.oldUrl=f);d!=m&&(s.newUrl=d);s.__history_shim__=p;if(!n&&a==m&&c.onpopstate)c.onpopstate(s);if(c.dispatchEvent&&!(10>P))c.dispatchEvent(s);else{var e;if(a=q[s.type])for(var b in a)a.hasOwnProperty(b)&&("function"==typeof(e=a[b])||e&&"object"==typeof e&&(e=e.handleEvent))&&e.call(c,s)}}function Y(a){return Q?a?Q.setItem("__history_shim__",Z(a)):na(Q.getItem("__history_shim__"))||{}:{}}function I(a,f,d){if(J)return J(a,f),a;if(d)return a;if(!d&&t){d="StaticClass"+t++;var b=["Class "+d],e;"execVB"in
c||c.execScript("Function execVB(c) ExecuteGlobal(c) End Function","VBScript");"VBCVal"in c||c.execScript("Function VBCVal(o,r) If IsObject(o) Then Set r=o Else r=o End If End Function","VBScript");for(e in a)E(a,e)&&b.push("Public ["+e+"]");E(a,"toString")&&(a.propertyIsEnumerable("toString")||b.push("Public [toString]"),f["(toString)"]={get:function(){return this.toString.call(this)}});for(e in f)E(f,e)&&(f[e].get&&(a["get "+e]=f[e].get,b.push("Public [get "+e+"]","Public "+("(toString)"===e?"Default ":
"")+"Property Get ["+e+"]","Call VBCVal(me.[get "+e+"].call(me),["+e+"])","End Property")),f[e].set&&(a["set "+e]=f[e].set,b.push("Public [set "+e+"]","Public Property Let ["+e+"](v)","Call me.[set "+e+"].call(me,v)","End Property","Public Property Set ["+e+"](v)","Call me.[set "+e+"].call(me,v)","End Property")));b.push("End Class","Function "+d+"Factory()","Set "+d+"Factory=New "+d,"End Function");c.execVB(b.join("\n"));b=c[d+"Factory"]();for(e in a)b[e]=a[e];E(a,"toString")&&(b.toString=a.toString)}return b}
function $(a,f,d,b){var c=Y(),l=j().a,h=d&&j(d);z=0;d=h?h.a:l;b&&c[l]&&delete c[l];if((!n||ra)&&Q&&a)c[d]=a,Y(c),a=w;aa&&R?b?R.call(this,a,f,d):P&&"/"==h.e?(aa.call(this,a,f,d+"?"),R.call(this,a,f,d)):aa.call(this,a,f,d):h&&h.f!=j().f&&(U=1,b?g.replace("#"+h.d):g.hash=h.d);a=j().c;if(!x||x!=a)G(3,x,a),x=a}function ba(a,f,d){this.pushState(a,f,d,1)}var c=this,b,u=document,O=u.documentElement,ca=Function.prototype.call,k=Function.prototype.bind||D,sa=u.documentMode&&/msie (\d+)/i.test(navigator.userAgent),
P=(b=c.opera)&&"function"==typeof(b=b.version)&&+b(),q;if(!c.addEventListener||10>P)q={popstate:{},hashchange:{}},q.onpopstate=q.popstate,q.onhashchange=q.hashchange,q.onpagechange=q.pagechange={},b=c.addEventListener?"addEventListener":"attachEvent",c[b]=k.call(function(a,f,d){var b,e;if(f in q){e=q[f];if(!(b=d.uuid))b=d.uuid="_"+ +new Date;e[b]||(e[b]=d)}ca.call(a,c,f,d,D)},c,c[b]),b=c.addEventListener?"removeEventListener":"detachEvent",c[b]=k.call(function(a,b,d){var s,e;b in q&&(s=d.uuid)&&(e=
q[b])&&delete e[s];ca.call(a,c,b,d,D)},c,c[b]);b=c.JSON||{};var na=b.parse,Z=b.stringify,H=c.j,E=k.call(ca,Object.prototype.hasOwnProperty),r=c.history||{},k=(b=c.history)&&(b=b.__proto__||(b=b.constructor)&&b.prototype)&&b&&b!=Object.prototype&&b||c.history,g=c.location,n="pushState"in r,ra=n&&r.state===m,z=g.href,aa=r.pushState,R=r.replaceState,Q=c.sessionStorage,J;if(b=Object.defineProperty&&function(a,b){var d,c;for(c in b)E(b,c)&&(d=b[c],"object"!=typeof d&&(d={value:d}),"configurable"in d||
(d.configurable=p),Object.defineProperty(a,c,d))}){try{b(k,{_:{get:function(){return 1},configurable:p}})}catch(va){b=w}1!==k._&&(b=w);"_"in k&&delete k._}!b&&k.__defineGetter__&&(b=function(a,b){var d,c;if(a.__defineGetter__)for(c in b)E(b,c)&&(d=b[c],d.get&&a.__defineGetter__(c,d.get),d.set&&a.__defineSetter__(c,d.set));return a});J=b;var t=!J&&c.execScript&&(new Date).getTime()||m,l=t?u.createElement("iframe"):0,U=0,ta=/[^\/]+$/g,ka=location.pathname.split("#")[0].split("?")[0],j,h=u.createElement("a"),
oa,da,pa,ea,S,K,y,ua=/^[^#]*/;j=function(a,b){if(a){if(!n||t||sa){var c=j(),l=c.e,e=c.i,k=a.charAt(0);a=/^(?:[\w0-9]+\:)?\/\//.test(a)?"/"==k?e+a:a:e+"//"+c.h+("/"==k?a:"?"==k?l+a:"#"==k?l+c.g+a:l.replace(ta,"")+a)}}else if(a=g.href,!n||b)a=g.protocol+"//"+g.host+(-1!=a.indexOf("#")?"/":ka)+(a.replace(ua,"")||"#").replace(/^#[\/]?(?:\/)?/,"");if(oa!==a){h.href=oa=a;K=h.port;S=h.host;y=h.pathname;if("http:"===h.protocol&&80==K||"https:"===h.protocol&&443==K)S=h.hostname,K="";y="/"==y.charAt(0)?y:"/"+
y;da=y+h.search+h.hash;ea=y+h.search;pa=ea+h.hash}return{a:h.protocol+"//"+S+da,i:h.protocol,h:S,k:h.hostname||g.hostname,l:K||g.port,e:y,g:h.search,b:h.hash,f:da,c:ea,d:pa}};b=!t&&k;var L=!b&&{back:r.back,forward:r.forward,go:r.go,pushState:$,replaceState:ba,emulate:!n,toString:function(){return"[object History]"}},A={state:{get:function(){return l&&l.storage||Y()[this.location.href]||w}},length:{get:function(){return r.length}},location:{set:function(a){c.location.href=a},get:function(){return n?
g:fa}}},fa={assign:function(a){g.assign(n||0!==a.indexOf("#")?a:"#"+j().c+a)},reload:g.reload,replace:function(a){g.replace(n||0!==a.indexOf("#")?a:"#"+j().c+a)},toString:function(){return this.href}},k={href:{set:function(a){g.href=a},get:function(){return j().a}},protocol:{set:function(a){g.protocol=a},get:function(){return g.protocol}},host:{set:function(a){g.host=a},get:function(){return g.host}},hostname:{set:function(a){g.hostname=a},get:function(){return g.hostname}},port:{set:function(a){g.port=
a},get:function(){return g.port}},pathname:{set:function(a){g.pathname=a},get:function(){return j().e}},search:{set:function(a){g.search=a},get:function(){return j().g}},hash:{set:function(a){a=0===a.indexOf("#")?a:"#"+a;var b=j();n?g.hash="#"+b.c+a:a!=b.b&&((L||r).pushState(w,w,b.c+a),ga({oldURL:b.a}))},get:function(){return j().b}},origin:{}},ga,qa=c.onpopstate||w,M=c.onhashchange,W=0,la=w,ja=j(),V=ja.a;c.addEventListener?c.addEventListener("hashchange",N,D):c.attachEvent("onhashchange",N);M===
m&&setInterval(function(){N({})},100);M||(M=w);c.addEventListener&&n&&(c.addEventListener("popstate",X,D),c.addEventListener("popstate",function(a){z=0;W=1;P&&R.call(r,a.state,document.title,location.href)},D));b?I(b,r.state===m?{state:A.state,location:A.location}:{location:A.location}):t&&(L=I(L,A));var A=I,B;a:{var C=fa;if(Object.defineProperty){try{if(Object.defineProperty(C,"_",{get:function(){return 1},configurable:p}),1===C._){delete C._;B=C;break a}}catch(wa){}B=document.createElement("a");
for(var v in B)try{delete B[v]}catch(xa){}for(v in C)B[v]=C[v]}else B=C}fa=A(B,k);t&&c.execScript("Public history, onhashchange","VBScript");!("onpopstate"in c||I(c,{onhashchange:{get:function(){return M},set:function(a){M=a||w}},onpopstate:{get:function(){return qa},set:function(a){(qa=a||w)&&!n&&ia()}}},p))&&!n&&(la=setInterval(function(){c.onpopstate&&ia()},100));n||(document.addEventListener?document.addEventListener("click",ma,D):document.attachEvent("onclick",ma));ga=N;try{new H("click")}catch(ya){H=
w}H||(H=function(a){var b;u.createEvent?(b=u.createEvent("Events"),b.initEvent(a,D,D)):(b=u.createEventObject(),b.type=a);return b});t||(b.pushState=$,b.replaceState=ba);if(t){c.history=L;v=u.cookie.split("__history_shim__=");var F=j().a,T,ha;if(l&&(ha=function(){var a=j().a;F!=a&&ga({oldURL:F,newURL:F=a})},T=setInterval(ha,100),l.src="javascript:true;",l=O.firstChild.appendChild(l).contentWindow,b.pushState=function(a,b,c,h,e){var k=l.document;if(c=c&&j(c)){e||clearInterval(T);if(h)l.lfirst?(history.back(),
this.pushState(a,b,c.a,0,1)):(l.storage=a,g.replace("#/"+c.d));else if(c.a!=F||e)l.lfirst||(l.lfirst=1,this.pushState(l.storage,b,F,0,1)),a=["<script>","lfirst=1;",0,"storage="+Z(a)+";","\x3c/script>"],a[2]='parent.location.hash="'+c.d.replace(/"/g,'\\"')+'";',k.open(),k.write(a.join("")),k.close();e||(F=j().a,T=setInterval(ha,100))}else l.storage=a},c.attachEvent("onunload",function(){if(l.storage){var a={};a[j().a]=l.storage;u.cookie="__history_shim__="+escape(Z(a))}clearInterval(T)}),1<v.length)){v=
unescape(v.pop().split(";").shift());try{l.storage=na(v)[j().a]}catch(za){}}}else b.emulate=!n;var x=j().c;b=function(){var a=j().c;if(!x||x!=a)G(3,x,a),x=a};c.addEventListener?(c.addEventListener("popstate",b,D),c.addEventListener("hashchange",b,D)):(c.attachEvent("popstate",b,D),c.attachEvent("hashchange",b,D));b=t=I=J=k=L=A=k=k=b=$=ba=w;
}.call(window);
