/*
 Copyright 2011-2013, github.com/termi/HTML5-History-API, original by Dmitriy Pakhtinov ( spb.piksel@gmail.com ) */
void function(){var p=void 0,r=!0,x=null,E=!1;function O(a){if(!a.__history_shim__){var d=j();if(T)return U=d.a,T=0;var c=a.oldURL||U;a=U=a.newURL||d.a;var d=c.replace(/^.*?(#|$)/,""),b=a.replace(/^.*?(#|$)/,"");c!=a&&!V&&H(p);A=V=0;d!=b&&H(2,c,a)}}function ga(){if(A&&!(A=0)&&ha.e!==ia)clearInterval(ja),setTimeout(H,10)}function ka(a){var d=a||b.event,c=d.target||d.srcElement;a="defaultPrevented"in d?d.defaultPrevented:d.returnValue===E;if(c&&("A"===c.nodeName&&!a)&&(a=j(c.getAttribute("href",2),r),a.b&&"#"!==a.b&&a.b===a.a.replace(j().a.split("#").shift(),
""))){history.location.hash=a.b;a=a.b.replace(/^#/,"");if((c=document.getElementById(a))&&c.id===a&&"A"===c.nodeName)c=c.getBoundingClientRect(),window.scrollTo(P.scrollLeft||0,c.top+(P.scrollTop||0)-(P.clientTop||0));d.preventDefault?d.preventDefault():d.returnValue=E}}function W(a){A===h.href&&(a.stopImmediatePropagation?a.stopImmediatePropagation():a.stopPropagation(),A=0);b.removeEventListener("popstate",W,E);W=x}function H(a,d,c){var k=new I(2==a?"hashchange":3==a?"pagechange":"popstate");d!=
p&&(k.oldUrl=d);c!=p&&(k.newUrl=c);k.__history_shim__=r;if(!l&&a==p&&b.onpopstate)b.onpopstate(k);if(b.dispatchEvent)b.dispatchEvent(k);else{var f;if(a=q[k.type])for(var e in a)a.hasOwnProperty(e)&&("function"==typeof(f=a[e])||f&&"object"==typeof f&&(f=f.handleEvent))&&f.call(b,k)}}function X(a){return Q?a?Q.setItem("__history_shim__",Y(a)):la(Q.getItem("__history_shim__"))||{}:{}}function J(a,d,c){if(K)return K(a,d),a;if(c)return a;if(!c&&s){c="StaticClass"+s++;var k=["Class "+c],f;"execVB"in b||
b.execScript("Function execVB(c) ExecuteGlobal(c) End Function","VBScript");"VBCVal"in b||b.execScript("Function VBCVal(o,r) If IsObject(o) Then Set r=o Else r=o End If End Function","VBScript");for(f in a)F(a,f)&&k.push("Public ["+f+"]");F(a,"toString")&&(a.propertyIsEnumerable("toString")||k.push("Public [toString]"),d["(toString)"]={get:function(){return this.toString.call(this)}});for(f in d)F(d,f)&&(d[f].get&&(a["get "+f]=d[f].get,k.push("Public [get "+f+"]","Public "+("(toString)"===f?"Default ":
"")+"Property Get ["+f+"]","Call VBCVal(me.[get "+f+"].call(me),["+f+"])","End Property")),d[f].set&&(a["set "+f]=d[f].set,k.push("Public [set "+f+"]","Public Property Let ["+f+"](v)","Call me.[set "+f+"].call(me,v)","End Property","Public Property Set ["+f+"](v)","Call me.[set "+f+"].call(me,v)","End Property")));k.push("End Class","Function "+c+"Factory()","Set "+c+"Factory=New "+c,"End Function");b.execVB(k.join("\n"));k=b[c+"Factory"]();for(f in a)k[f]=a[f];F(a,"toString")&&(k.toString=a.toString)}return k}
function Z(a,d,c,b){var f=X(),e=j().a,g=c&&j(c);A=0;c=g?g.a:e;b&&f[e]&&delete f[e];if((!l||ra)&&Q&&a)f[c]=a,X(f),a=x;ma&&na?b?na.call(this,a,d,c):ma.call(this,a,d,c):g&&g.e!=j().e&&(T=1,b?h.replace("#"+g.d):h.hash=g.d);a=j().c;if(!y||y!=a)H(3,y,a),y=a}function $(a,d,c){this.pushState(a,d,c,1)}var b=this,e=b.JSON||{},la=e.parse,Y=e.stringify,v=document,P=v.documentElement,I=b.j,w=Function.prototype.bind||E,aa=Function.prototype.call,F=w.call(aa,Object.prototype.hasOwnProperty),t=b.history||{},g=(e=
b.history)&&(e=e.__proto__||(e=e.constructor)&&e.prototype)&&e&&e!=Object.prototype&&e||b.history,h=b.location,l="pushState"in t,ra=l&&t.state===p,A=h.href,ma=t.pushState,na=t.replaceState,Q=b.sessionStorage,K;if(e=Object.defineProperty&&function(a,d){var c,b;for(b in d)F(d,b)&&(c=d[b],"object"!=typeof c&&(c={value:c}),"configurable"in c||(c.configurable=r),Object.defineProperty(a,b,c))}){try{e(g,{_:{get:function(){return 1},configurable:r}})}catch(va){e=x}1!==g._&&(e=x);"_"in g&&delete g._}!e&&g.__defineGetter__&&
(e=function(a,d){var c,b;if(a.__defineGetter__)for(b in d)F(d,b)&&(c=d[b],c.get&&a.__defineGetter__(b,c.get),c.set&&a.__defineSetter__(b,c.set));return a});K=e;var sa=v.documentMode&&/msie (\d+)/i.test(navigator.userAgent),s=!K&&b.execScript&&(new Date).getTime()||p,m=s?v.createElement("iframe"):0,q,T=0,ta=/[^\/]+$/g,ia=location.pathname.split("#")[0].split("?")[0],j,n=v.createElement("a"),oa,ba,pa,ca,R,L,z,ua=/^[^#]*/;j=function(a,b){if(a){if(!l||s||sa){var c=j(),e=c.f,f=c.i,g=a.charAt(0);a=/^(?:[\w0-9]+\:)?\/\//.test(a)?
"/"==g?f+a:a:f+"//"+c.h+("/"==g?a:"?"==g?e+a:"#"==g?e+c.g+a:e.replace(ta,"")+a)}}else if(a=h.href,!l||b)a=h.protocol+"//"+h.host+(-1!=a.indexOf("#")?"/":ia)+(a.replace(ua,"")||"#").replace(/^#[\/]?(?:\/)?/,"");if(oa!==a){n.href=oa=a;L=n.port;R=n.host;z=n.pathname;if("http:"===n.protocol&&80==L||"https:"===n.protocol&&443==L)R=n.hostname,L="";z="/"==z.charAt(0)?z:"/"+z;ba=z+n.search+n.hash;ca=z+n.search;pa=ca+n.hash}return{a:n.protocol+"//"+R+ba,i:n.protocol,h:R,k:n.hostname||h.hostname,l:L||h.port,
f:z,g:n.search,b:n.hash,e:ba,c:ca,d:pa}};var g=!s&&g,M=!g&&{back:t.back,forward:t.forward,go:t.go,pushState:Z,replaceState:$,emulate:!l,toString:function(){return"[object History]"}},B={state:{get:function(){return m&&m.storage||X()[this.location.href]||x}},length:{get:function(){return t.length}},location:{set:function(a){b.location.href=a},get:function(){return l?h:da}}},da={assign:function(a){h.assign(l||0!==a.indexOf("#")?a:"#"+j().c+a)},reload:h.reload,replace:function(a){h.replace(l||0!==a.indexOf("#")?
a:"#"+j().c+a)},toString:function(){return this.href}},e={href:{set:function(a){h.href=a},get:function(){return j().a}},protocol:{set:function(a){h.protocol=a},get:function(){return h.protocol}},host:{set:function(a){h.host=a},get:function(){return h.host}},hostname:{set:function(a){h.hostname=a},get:function(){return h.hostname}},port:{set:function(a){h.port=a},get:function(){return h.port}},pathname:{set:function(a){h.pathname=a},get:function(){return j().f}},search:{set:function(a){h.search=a},
get:function(){return j().g}},hash:{set:function(a){a=0===a.indexOf("#")?a:"#"+a;var b=j();l?h.hash="#"+b.c+a:a!=b.b&&((M||t).pushState(x,x,b.c+a),ea({oldURL:b.a}))},get:function(){return j().b}},origin:{}},ea,qa=b.onpopstate||x,N=b.onhashchange,V=0,ja=x,ha=j(),U=ha.a;b.addEventListener?b.addEventListener("hashchange",O,E):b.attachEvent("onhashchange",O);N===p&&setInterval(function(){O({})},100);N||(N=x);b.addEventListener&&l&&(b.addEventListener("popstate",W,E),b.addEventListener("popstate",function(){A=
0;V=1},E));g?J(g,t.state===p?{state:B.state,location:B.location}:{location:B.location}):s&&(M=J(M,B));var B=J,u;a:{var C=da;if(Object.defineProperty){try{if(Object.defineProperty(C,"_",{get:function(){return 1},configurable:r}),1===C._){delete C._;u=C;break a}}catch(wa){}u=document.createElement("a");for(var D in u)try{delete u[D],D in u&&u[D]&&(u[D]=x)}catch(xa){}for(D in C)u[D]=C[D]}else u=C}da=B(u,e);s&&b.execScript("Public history, onhashchange","VBScript");!("onpopstate"in b||J(b,{onhashchange:{get:function(){return N},
set:function(a){N=a||x}},onpopstate:{get:function(){return qa},set:function(a){(qa=a||x)&&!l&&ga()}}},r))&&!l&&(ja=setInterval(function(){b.onpopstate&&ga()},100));l||(document.addEventListener?document.addEventListener("click",ka,E):document.attachEvent("onclick",ka));ea=O;try{new I("click")}catch(ya){I=x}I||(I=function(a){var b;v.createEvent?(b=v.createEvent("Events"),b.initEvent(a,E,E)):(b=v.createEventObject(),b.type=a);return b});b.addEventListener||(q={popstate:{},hashchange:{}},q.onpopstate=
q.popstate,q.onhashchange=q.hashchange,q.onpagechange=q.pagechange={},b.attachEvent=w.call(function(a,d,c){if(d in q){d=q[d];if(!(a=c.uuid))a=c.uuid="_"+ +new Date;d[a]||(d[a]=c)}else aa.call(a,b,d,c)},b,b.attachEvent),b.detachEvent=w.call(function(a,d,c){var e;d in q?(a=c.uuid)&&(e=q[d])&&delete e[a]:aa.call(a,b,d,c)},b,b.detachEvent));s||(g.pushState=Z,g.replaceState=$);if(s){b.history=M;var w=v.cookie.split("__history_shim__="),G=j().a,S,fa;if(m&&(fa=function(){var a=j().a;G!=a&&ea({oldURL:G,newURL:G=
a})},S=setInterval(fa,100),m.src="javascript:true;",m=P.firstChild.appendChild(m).contentWindow,g.pushState=function(a,b,c,e,f){var g=m.document;if(c=c&&j(c)){f||clearInterval(S);if(e)m.lfirst?(history.back(),this.pushState(a,b,c.a,0,1)):(m.storage=a,h.replace("#/"+c.d));else if(c.a!=G||f)m.lfirst||(m.lfirst=1,this.pushState(m.storage,b,G,0,1)),a=["<script>","lfirst=1;",,"storage="+Y(a)+";","\x3c/script>"],a[2]='parent.location.hash="'+c.d.replace(/"/g,'\\"')+'";',g.open(),g.write(a.join("")),g.close();
f||(G=j().a,S=setInterval(fa,100))}else m.storage=a},b.attachEvent("onunload",function(){if(m.storage){var a={};a[j().a]=m.storage;v.cookie="__history_shim__="+escape(Y(a))}clearInterval(S)}),1<w.length)){w=unescape(w.pop().split(";").shift());try{m.storage=la(w)[j().a]}catch(za){}}}else g.emulate=!l;var y="",e=function(){var a=j().c;if(!y||y!=a)y=a,H(3,y,a)};b.addEventListener?(l&&b.addEventListener("popstate",e),b.addEventListener("hashchange",e)):(l&&b.attachEvent("popstate",e),b.attachEvent("hashchange",
e));if(b.opera&&l&&(e=document.createElement("a"),g=e.__proto__))(e=Object.getOwnPropertyDescriptor(e,"href"))&&"get"in e&&Object.defineProperty(g,"href",function(a){this.get=function(){var d=this.getAttribute("href"),c;return d&&"/"==d[0]?(c=b.location,c=c.protocol+"//"+c.host,c+d):a.call(this)};return this}.call(e,e.get));e=s=J=K=w=M=B=e=g=g=Z=$=x}.call(window);
