/*Copyright 2011-2013, Dmitriy Pakhtinov ( spb.piksel@gmail.com ) and github.com/termi */
void function(){var t=void 0,u=null,v=!1;function B(a,b,e){var f=new C(2==a?"hashchange":3==a?"pagechange":"popstate");b!=t&&(f.oldUrl=b);e!=t&&(f.newUrl=e);f.__history_shim__=!0;if(!n&&a==t&&c.onpopstate)c.onpopstate(f);if(c.dispatchEvent)c.dispatchEvent(f);else{var d;if(a=k[f.type])for(var p in a)a.hasOwnProperty(p)&&("function"==typeof(d=a[p])||d&&"object"==typeof d&&(d=d.handleEvent))&&d.call(c,f)}}function M(a){return F?a?F.setItem("__hitoryapi__",q(a)):G(F.getItem("__hitoryapi__"))||{}:{}}function H(a,b,e){var f=a,
d,p=v;try{if(1!==Object.defineProperty({},"t",{get:function(){return 1}}).t)throw Error;Object.defineProperties(a,b)}catch(h){if(a.__defineGetter__)for(var m in b)I(b,m)&&(a.__defineGetter__(m,b[m].get),b[m].set&&a.__defineSetter__(m,b[m].set));if(e)return v;p=!0}if(!e&&p&&z){e="StaticClass"+R+z++;f=["Class "+e];"execVB"in c||execScript("Function execVB(c) ExecuteGlobal(c) End Function","VBScript");"VBCVal"in c||execScript("Function VBCVal(o,r) If IsObject(o) Then Set r=o Else r=o End If End Function",
"VBScript");for(d in a)f.push("Public ["+d+"]");I(a,"toString")&&(a.propertyIsEnumerable("toString")||f.push("Public [toString]"),b["(toString)"]={get:function(){return this.toString.call(this)}});for(d in b)I(b,d)&&(b[d].get&&(a["get "+d]=b[d].get,f.push("Public [get "+d+"]","Public "+("(toString)"===d?"Default ":"")+"Property Get ["+d+"]","Call VBCVal(me.[get "+d+"].call(me),["+d+"])","End Property")),b[d].set&&(a["set "+d]=b[d].set,f.push("Public [set "+d+"]","Public Property Let ["+d+"](v)","Call me.[set "+
d+"].call(me,v)","End Property","Public Property Set ["+d+"](v)","Call me.[set "+d+"].call(me,v)","End Property")));f.push("End Class","Function "+e+"Factory()","Set "+e+"Factory=New "+e,"End Function");execVB(f.join("\n"));f=c[e+"Factory"]();for(d in a)f[d]=a[d];I(a,"toString")&&(f.toString=a.toString)}return f}var c=this,w=c.JSON||{},x=document,J=x.documentElement,C=c.j,N=Function.prototype.bind||function(a,b){var e=this,c=S.call(arguments,1);return function(){return _Function_apply.call(e,a,c.concat(S.call(arguments)))}},
S=Array.prototype.slice,O=Function.prototype.call,I=N.call(O,Object.prototype.hasOwnProperty),s=c.history||{},h=c.location,n="pushState"in s,X=n&&s.state===t,A=h.href,T=s.pushState,U=s.replaceState,G=w.parse,q=w.stringify,F=c.sessionStorage,E=c.eval&&eval("/*@cc_on 1;@*/")&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||t,R=(new Date).getTime(),z=!E||8<E?0:1,g=8>E?x.createElement("iframe"):0,k,P=0,Y=/[^\/]+$/g,V=location.pathname.split("#")[0].split("?")[0],j=function(a){var b,c,f,d,p,D,
m,g=/^[^#]*/,r=/^(?:[a-z]+\:)?\/\//;return function(l,Z){if(l){if(!n||E){var K=j(),k=K.f,s=K.i,q=l.charAt(0);l=r.test(l)?"/"==q?s+l:l:s+"//"+K.h+("/"==q?l:"?"==q?k+l:"#"==q?k+K.g+l:k.replace(Y,"")+l)}}else if(l=h.href,!n||Z)l=h.protocol+"//"+h.host+(-1!=l.indexOf("#")?"/":V)+(l.replace(g,"")||"#").replace(/^#[\/]?(?:\/)?/,"");if(b!==l){a.href=b=l;D=a.port;p=a.host;m=a.pathname;if("http:"===a.protocol&&80==D||"https:"===a.protocol&&443==D)p=a.hostname,D="";m="/"==m.charAt(0)?m:"/"+m;c=m+a.search+a.hash;
d=m+a.search;f=d+a.hash}return{a:a.protocol+"//"+p+c,i:a.protocol,h:p,k:a.hostname||h.hostname,l:D||h.port,f:m,g:a.search,b:a.hash,e:c,c:d,d:f}}}(x.createElement("a")),r=!z&&s||{back:s.back,forward:s.forward,go:s.go,pushState:t,replaceState:t,emulate:!n,toString:function(){return"[object History]"}},L={state:{get:function(){return g&&g.storage||M()[r.location.href]||u}},length:{get:function(){return s.length}},location:{set:function(a){c.location=a},get:function(){return n?h:Q}}},Q={assign:function(a){h.assign(n||
0!==a.indexOf("#")?a:"#"+j().c+a)},reload:h.reload,replace:function(a){h.replace(n||0!==a.indexOf("#")?a:"#"+j().c+a)},toString:function(){return this.href}},$={href:{set:function(a){h.href=a},get:function(){return j().a}},protocol:{set:function(a){h.protocol=a},get:function(){return h.protocol}},host:{set:function(a){h.host=a},get:function(){return h.host}},hostname:{set:function(a){h.hostname=a},get:function(){return h.hostname}},port:{set:function(a){h.port=a},get:function(){return h.port}},pathname:{set:function(a){h.pathname=
a},get:function(){return j().f}},search:{set:function(a){h.search=a},get:function(){return j().g}},hash:{set:function(a){a=0===a.indexOf("#")?a:"#"+a;var b=j();g?a!=b.b&&(r.pushState(u,u,b.c+a),W({oldURL:b.a})):h.hash="#"+b.c+a},get:function(){return j().b}},origin:{}},W=function(){function a(a){if(!a.__history_shim__){var b=j();if(P)return q=b.a,P=0;var c=a.oldURL||q;a=q=a.newURL||b.a;var b=c.replace(/^.*?(#|$)/,""),e=a.replace(/^.*?(#|$)/,"");c!=a&&!g&&B(t);A=g=0;b!=e&&B(2,c,a)}}function b(){if(A&&
!(A=0)&&k.e!==V)clearInterval(m),setTimeout(B,10)}function e(a){A===h.href&&(a.stopImmediatePropagation?a.stopImmediatePropagation():a.stopPropagation(),A=0);c.removeEventListener("popstate",e,v)}function f(a){var b=a||c.event,e=b.target||b.srcElement;a="defaultPrevented"in b?b.defaultPrevented:b.returnValue===v;if(e&&("A"===e.nodeName&&!a)&&(a=j(e.getAttribute("href",2),!0),a.b&&"#"!==a.b&&a.b===a.a.replace(j().a.split("#").shift(),""))){history.location.hash=a.b;a=a.b.replace(/^#/,"");if((e=document.getElementById(a))&&
e.id===a&&"A"===e.nodeName)e=e.getBoundingClientRect(),window.scrollTo(J.scrollLeft||0,e.top+(J.scrollTop||0)-(J.clientTop||0));b.preventDefault?b.preventDefault():b.returnValue=v}}var d=c.onpopstate||u,p=c.onhashchange||u,g=0,m=u,k=j(),q=k.a;c.addEventListener?c.addEventListener("hashchange",a,v):c.attachEvent("onhashchange",a);c.addEventListener&&(c.addEventListener("popstate",e,v),c.addEventListener("popstate",function(){A=0;g=1},v));r=H(r,z?L:s.state===t?{state:L.state,location:L.location}:{location:L.location});
Q=H(Q,$);z&&execScript("Public history, onhashchange","VBScript");!("onpopstate"in c||H(c,{onhashchange:{get:function(){return p},set:function(a){p=a||u}},onpopstate:{get:function(){return d},set:function(a){(d=a||u)&&!n&&b()}}},!0))&&!n&&(m=setInterval(function(){c.onpopstate&&b()},100));n||(document.addEventListener?document.addEventListener("click",f,v):document.attachEvent("onclick",f));return a}();q||(q=function(a,b,c){for(b in(c="[object Object]"==a&&[])&&a)c.push(q(b)+":"+q(a[b]));return""+
a===a?'"'+a+'"':a&&a.map?"["+a.map(q)+"]":c?"{"+c+"}":a});G||(G=function(a){return a?(new Function("return "+a))():u});try{new C("click")}catch(aa){C=u}C||(C=function(a){var b;x.createEvent?(b=x.createEvent("Events"),b.initEvent(a,v,v)):(b=x.createEventObject(),b.type=a);return b});c.addEventListener||(k={popstate:{},hashchange:{}},k.onpopstate=k.popstate,k.onhashchange=k.hashchange,k.onpagechange=k.pagechange={},c.attachEvent=N.call(function(a,b,e){if(b in k){b=k[b];if(!(a=e.uuid))a=e.uuid="_"+ +new Date;
b[a]||(b[a]=e)}else O.call(a,c,b,e)},c,c.attachEvent),c.detachEvent=N.call(function(a,b,e){var f;b in k?(a=e.uuid)&&(f=k[b])&&delete f[a]:O.call(a,c,b,e)},c,c.detachEvent));r.pushState=function(a,b,c,f){var d=M(),p=j().a,g=c&&j(c);A=0;c=g?g.a:p;f&&d[p]&&delete d[p];if((!n||X)&&F&&a)d[c]=a,M(d),a=u;T&&U?f?U.call(r,a,b,c):T.call(r,a,b,c):g&&g.e!=j().e&&(P=1,f?h.replace("#"+g.d):h.hash=g.d);a=j().c;if(!y||y!=a)B(3,y,a),y=a};r.replaceState=function(a,b,c){r.pushState(a,b,c,1)};z?(c.history=r,function(a,
b){var e,f;if(g&&(f=function(){var a=j().a;b!=a&&W({oldURL:b,newURL:b=a})},e=setInterval(f,100),g.src="javascript:true;",g=J.firstChild.appendChild(g).contentWindow,r.pushState=function(a,c,d,k,n){var l=g.document;if(d=d&&j(d)){n||clearInterval(e);if(k)g.lfirst?(history.back(),r.pushState(a,c,d.a,0,1)):(g.storage=a,h.replace("#/"+d.d));else if(d.a!=b||n)g.lfirst||(g.lfirst=1,r.pushState(g.storage,c,b,0,1)),a=["<script>","lfirst=1;",,"storage="+q(a)+";","\x3c/script>"],a[2]='parent.location.hash="'+
d.d.replace(/"/g,'\\"')+'";',l.open(),l.write(a.join("")),l.close();n||(b=j().a,e=setInterval(f,100))}else g.storage=a},c.attachEvent("unload",function(){if(g.storage){var a={};a[j().a]=g.storage;x.cookie="_historyAPI="+escape(q(a))}clearInterval(e)}),1<a.length)){a=unescape(a.pop().split(";").shift());try{g.storage=G(a)[j().a]}catch(d){}}}(x.cookie.split("_historyAPI="),j().a)):c.history.emulate=!n;var y="",w=function(){var a=j().c;if(!y||y!=a)B(3,y,a),y=a};c.addEventListener?(c.addEventListener("popstate",
w),c.addEventListener("hashchange",w)):(c.attachEvent("popstate",w),c.attachEvent("hashchange",w));w=E=R=z=H=t}.call(window);
