/*
 Copyright 2011-2013, github.com/termi/HTML5-History-API, original by Dmitriy Pakhtinov ( spb.piksel@gmail.com ) */
void function(){"use strict";var m=void 0,n=!0,q=null,x=!1;function E(a){if(!a.__history_shim__){var f=j();if(K)return L=f.a,K=0;var d=a.oldURL||L;a=L=a.newURL||f.a;var f=d.replace(/^.*?(#|$)/,""),b=a.replace(/^.*?(#|$)/,"");d!=a&&!M&&A(m);t=M=0;f!=b&&A(2,d,a)}}function V(){if(t&&!(t=0)&&W.d!==X)clearInterval(Y),setTimeout(A,10)}function Z(a){var f=a||b.event,d=f.target||f.srcElement;a="defaultPrevented"in f?f.defaultPrevented:f.returnValue===x;if(d&&("A"===d.nodeName&&!a)&&(a=j(d.getAttribute("href",2),n),a.b&&"#"!==a.b&&a.b===a.a.replace(j().a.split("#").shift(),
""))){history.location.hash=a.b;a=a.b.replace(/^#/,"");if((d=document.getElementById(a))&&d.id===a&&"A"===d.nodeName)d=d.getBoundingClientRect(),window.scrollTo(N.scrollLeft||0,d.top+(N.scrollTop||0)-(N.clientTop||0));f.preventDefault?f.preventDefault():f.returnValue=x}}function O(a){t===e.href&&(a.stopImmediatePropagation?a.stopImmediatePropagation():a.stopPropagation(),t=0);b.removeEventListener("popstate",O,x);O=q}function A(a,f,d){var c=new B(2==a?"hashchange":3==a?"pagechange":"popstate");f!=
m&&(c.oldUrl=f);d!=m&&(c.newUrl=d);c.__history_shim__=n;if(!k&&a==m&&b.onpopstate)b.onpopstate(c);if(b.dispatchEvent)b.dispatchEvent(c);else{var e;if(a=l[c.type])for(var j in a)a.hasOwnProperty(j)&&("function"==typeof(e=a[j])||e&&"object"==typeof e&&(e=e.handleEvent))&&e.call(b,c)}}function P(a){return F?a?F.setItem("__history_shim__",ja(a)):ka(F.getItem("__history_shim__"))||{}:{}}function G(a,f,d){return H?(H(a,f),a):d?a:m}function $(a,f,d,b){var c=P(),g=j().a,h=d&&j(d);t=0;d=h?h.a:g;b&&c[g]&&delete c[g];
if((!k||la)&&F&&a)c[d]=a,P(c),a=q;aa&&ba?b?ba.call(this,a,f,d):aa.call(this,a,f,d):h&&h.d!=j().d&&(K=1,b?e.replace("#"+h.g):e.hash=h.g);a=j().c;if(!r||r!=a)A(3,r,a),r=a}function ca(a,f,d){this.pushState(a,f,d,1)}var b=this,c=b.JSON||{},ka=c.parse,ja=c.stringify,y=document,N=y.documentElement,B=b.j,I=Function.prototype.bind||x,Q=Function.prototype.call,da=I.call(Q,Object.prototype.hasOwnProperty),u=b.history||{},g=(c=b.history)&&(c=c.__proto__||(c=c.constructor)&&c.prototype)&&c&&c!=Object.prototype&&
c||b.history,e=b.location,k="pushState"in u,la=k&&u.state===m,t=e.href,aa=u.pushState,ba=u.replaceState,F=b.sessionStorage,H;if(c=Object.defineProperty&&function(a,f){var d,b;for(b in f)da(f,b)&&(d=f[b],"object"!=typeof d&&(d={value:d}),"configurable"in d||(d.configurable=n),Object.defineProperty(a,b,d))}){try{c(g,{_:{get:function(){return 1},configurable:n}})}catch(pa){c=q}1!==g._&&(c=q);"_"in g&&delete g._}!c&&g.__defineGetter__&&(c=function(a,f){var d,b;if(a.__defineGetter__)for(b in f)da(f,b)&&
(d=f[b],d.get&&a.__defineGetter__(b,d.get),d.set&&a.__defineSetter__(b,d.set));return a});H=c;var ma=y.documentMode&&/msie (\d+)/i.test(navigator.userAgent),R=m,l,K=0,na=/[^\/]+$/g,X=location.pathname.split("#")[0].split("?")[0],j,h=y.createElement("a"),ea,S,fa,T,J,C,s,oa=/^[^#]*/;j=function(a,b){if(a){if(!k||R||ma){var d=j(),c=d.e,g=d.i,l=a.charAt(0);a=/^(?:[\w0-9]+\:)?\/\//.test(a)?"/"==l?g+a:a:g+"//"+d.h+("/"==l?a:"?"==l?c+a:"#"==l?c+d.f+a:c.replace(na,"")+a)}}else if(a=e.href,!k||b)a=e.protocol+
"//"+e.host+(-1!=a.indexOf("#")?"/":X)+(a.replace(oa,"")||"#").replace(/^#[\/]?(?:\/)?/,"");if(ea!==a){h.href=ea=a;C=h.port;J=h.host;s=h.pathname;if("http:"===h.protocol&&80==C||"https:"===h.protocol&&443==C)J=h.hostname,C="";s="/"==s.charAt(0)?s:"/"+s;S=s+h.search+h.hash;T=s+h.search;fa=T+h.hash}return{a:h.protocol+"//"+J+S,i:h.protocol,h:J,k:h.hostname||e.hostname,l:C||e.port,e:s,f:h.search,b:h.hash,d:S,c:T,g:fa}};var g=!R&&g,ga=x,z={state:{get:function(){return P()[this.location.href]||q}},length:{get:function(){return u.length}},
location:{set:function(a){b.location.href=a},get:function(){return k?e:U}}},U={assign:function(a){e.assign(k||0!==a.indexOf("#")?a:"#"+j().c+a)},reload:e.reload,replace:function(a){e.replace(k||0!==a.indexOf("#")?a:"#"+j().c+a)},toString:function(){return this.href}},c={href:{set:function(a){e.href=a},get:function(){return j().a}},protocol:{set:function(a){e.protocol=a},get:function(){return e.protocol}},host:{set:function(a){e.host=a},get:function(){return e.host}},hostname:{set:function(a){e.hostname=
a},get:function(){return e.hostname}},port:{set:function(a){e.port=a},get:function(){return e.port}},pathname:{set:function(a){e.pathname=a},get:function(){return j().e}},search:{set:function(a){e.search=a},get:function(){return j().f}},hash:{set:function(a){a=0===a.indexOf("#")?a:"#"+a;var b=j();k?e.hash="#"+b.c+a:a!=b.b&&((ga||u).pushState(q,q,b.c+a),ha({oldURL:b.a}))},get:function(){return j().b}},origin:{}},ha,ia=b.onpopstate||q,D=b.onhashchange,M=0,Y=q,W=j(),L=W.a;b.addEventListener?b.addEventListener("hashchange",
E,x):b.attachEvent("onhashchange",E);D===m&&setInterval(function(){E({})},100);D||(D=q);b.addEventListener&&k&&(b.addEventListener("popstate",O,x),b.addEventListener("popstate",function(){t=0;M=1},x));g&&G(g,u.state===m?{state:z.state,location:z.location}:{location:z.location});var z=G,p;a:{var v=U;if(Object.defineProperty){try{if(Object.defineProperty(v,"_",{get:function(){return 1},configurable:n}),1===v._){delete v._;p=v;break a}}catch(qa){}p=document.createElement("a");for(var w in p)try{delete p[w],
w in p&&p[w]&&(p[w]=q)}catch(ra){}for(w in v)p[w]=v[w]}else p=v}U=z(p,c);!("onpopstate"in b||G(b,{onhashchange:{get:function(){return D},set:function(a){D=a||q}},onpopstate:{get:function(){return ia},set:function(a){(ia=a||q)&&!k&&V()}}},n))&&!k&&(Y=setInterval(function(){b.onpopstate&&V()},100));k||(document.addEventListener?document.addEventListener("click",Z,x):document.attachEvent("onclick",Z));ha=E;try{new B("click")}catch(sa){B=q}B||(B=function(a){var b;y.createEvent?(b=y.createEvent("Events"),
b.initEvent(a,x,x)):(b=y.createEventObject(),b.type=a);return b});b.addEventListener||(l={popstate:{},hashchange:{}},l.onpopstate=l.popstate,l.onhashchange=l.hashchange,l.onpagechange=l.pagechange={},b.attachEvent=I.call(function(a,c,d){if(c in l){c=l[c];if(!(a=d.uuid))a=d.uuid="_"+ +new Date;c[a]||(c[a]=d)}else Q.call(a,b,c,d)},b,b.attachEvent),b.detachEvent=I.call(function(a,c,d){var e;c in l?(a=d.uuid)&&(e=l[c])&&delete e[a]:Q.call(a,b,c,d)},b,b.detachEvent));g.pushState=$;g.replaceState=ca;g.emulate=
!k;var r="",c=function(){var a=j().c;if(!r||r!=a)r=a,A(3,r,a)};b.addEventListener?(k&&b.addEventListener("popstate",c),b.addEventListener("hashchange",c)):(k&&b.attachEvent("popstate",c),b.attachEvent("hashchange",c));if(b.opera&&k&&(c=document.createElement("a"),g=c.__proto__))(c=Object.getOwnPropertyDescriptor(c,"href"))&&"get"in c&&Object.defineProperty(g,"href",function(a){this.get=function(){var c=this.getAttribute("href"),d;return c&&"/"==c[0]?(d=b.location,d=d.protocol+"//"+d.host,d+c):a.call(this)};
return this}.call(c,c.get));c=R=G=H=I=ga=z=c=g=g=$=ca=q}.call(window);
